baseurl: /chicago
permalink: pretty
markdown: kramdown
paginate: 5
repo: chicago
github_org: maptime
future: true
maptime:
  chapter: Maptime Chicago
  twitter: maptimeCHI
  #disqus: YOUR DISQUS USERNAME
